server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/music-service-db
    username: secret
    password: secret
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enable: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9002
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: interaction-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka