server:
  port: 8086

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka