global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'metrics-processor'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8089'] # Имя сервиса из docker-compose и его порт
        labels:
          application: 'metric-service'
          instance: 'local-host-instance'