spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bookdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8080